# Generated by Django 4.2.5 on 2023-10-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_code', models.CharField(max_length=255, verbose_name='Аббревиатура наименования города')),
                ('Name_RUS', models.CharField(max_length=255, verbose_name='Наименования города (RUS)')),
                ('Name_ENG', models.CharField(max_length=255, verbose_name='Наименования города (ENG)')),
                ('Name_DEU', models.CharField(max_length=255, verbose_name='Наименования города (DEU)')),
                ('Name_SRB', models.CharField(max_length=255, verbose_name='Наименования города (SRB)')),
                ('Country', models.CharField(max_length=255, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['City_code'],
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactType_code', models.CharField(max_length=255, verbose_name='Аббревиатура типа пользователя')),
                ('Name_RUS', models.CharField(max_length=255, verbose_name='Наименования типа пользователя (RUS)')),
                ('Name_ENG', models.CharField(max_length=255, verbose_name='Наименования типа пользователя (ENG)')),
                ('Name_DEU', models.CharField(max_length=255, verbose_name='Наименования типа пользователя (DEU)')),
                ('Name_SRB', models.CharField(max_length=255, verbose_name='Наименования типа пользователя (SRB)')),
            ],
            options={
                'verbose_name': 'Тип пользователя',
                'verbose_name_plural': 'Типы пользователя',
                'ordering': ['ContactType_code'],
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_code', models.CharField(max_length=255, verbose_name='Аббревиатура наименования страны')),
                ('Name_RUS', models.CharField(max_length=255, verbose_name='Наименования страны (RUS)')),
                ('Name_ENG', models.CharField(max_length=255, verbose_name='Наименования города (ENG)')),
                ('Name_DEU', models.CharField(max_length=255, verbose_name='Наименования города (DEU)')),
                ('Name_SRB', models.CharField(max_length=255, verbose_name='Наименования города (SRB)')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['Country_code'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Currency_code', models.CharField(max_length=255, verbose_name='Аббревиатура валюты')),
                ('Name_RUS', models.CharField(max_length=255, verbose_name='Наименования валюты (RUS)')),
                ('Name_ENG', models.CharField(max_length=255, verbose_name='Наименования валюты (ENG)')),
                ('Name_DEU', models.CharField(max_length=255, verbose_name='Наименования валюты (DEU)')),
                ('Name_SRB', models.CharField(max_length=255, verbose_name='Наименования валюты (SRB)')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['Currency_code'],
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=255, verbose_name='ID пользователя')),
                ('ip', models.CharField(blank=True, max_length=255, verbose_name='IP-адрес')),
                ('Country_code', models.CharField(max_length=255, verbose_name='Код страны пользователя')),
                ('Language_code', models.CharField(max_length=255, verbose_name='Код языка пользователя')),
                ('email', models.CharField(max_length=255, verbose_name='Email пользователя')),
                ('Name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('PCCNTR', models.CharField(blank=True, max_length=255, verbose_name='Центр прибыли и затрат')),
                ('ExchangePointID', models.CharField(blank=True, max_length=255, verbose_name='ID обменника')),
                ('Text', models.CharField(max_length=2000, verbose_name='Текст')),
                ('Rating', models.FloatField(verbose_name='Оценка')),
                ('Active', models.IntegerField(default=1, verbose_name='На модерации (1 - нет; 0 - да , -1 - удален)')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Время отправления')),
                ('Comment', models.CharField(blank=True, max_length=2000, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['User'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender_code', models.CharField(max_length=255, verbose_name='Аббревиатура наименования гендера')),
                ('Name_RUS', models.CharField(max_length=255, verbose_name='Наименования гендера (RUS)')),
                ('Name_ENG', models.CharField(max_length=255, verbose_name='Наименования гендера (ENG)')),
                ('Name_DEU', models.CharField(max_length=255, verbose_name='Наименования гендера (DEU)')),
                ('Name_SRB', models.CharField(max_length=255, verbose_name='Наименования гендера (SRB)')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
                'ordering': ['Gender_code'],
            },
        ),
        migrations.CreateModel(
            name='PCCNTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCCNTR_code', models.CharField(blank=True, max_length=255, verbose_name='Код обменника')),
                ('PCCNTR_name', models.CharField(max_length=255, verbose_name='Наименования обменника')),
            ],
            options={
                'verbose_name': 'Центр прибыли и затрат',
                'verbose_name_plural': 'Центры прибыли и затрат',
                'ordering': ['PCCNTR_code'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TG_Contact', models.CharField(blank=True, max_length=255, verbose_name='Ник в Телеграм')),
                ('user_ID', models.CharField(blank=True, max_length=255, verbose_name='ID в Телеграм')),
                ('ip', models.CharField(blank=True, max_length=255, verbose_name='IP-адрес')),
                ('Name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('Surname', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('Otchestvo', models.CharField(blank=True, max_length=255, verbose_name='Отчество (при наличии)')),
                ('registeredDate', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('ContactType', models.CharField(blank=True, max_length=255, verbose_name='Тип контакта')),
                ('GENDER', models.CharField(blank=True, max_length=255, verbose_name='Пол')),
                ('COUNTRY', models.CharField(blank=True, max_length=255, verbose_name='Страна')),
                ('CITY', models.CharField(blank=True, max_length=255, verbose_name='Город')),
                ('SUBSCRIPTION', models.CharField(blank=True, max_length=255, verbose_name='Подписка')),
                ('ACTIVE', models.IntegerField(blank=True, default=1, verbose_name='Статус пользователя')),
                ('VERIFIED', models.CharField(blank=True, max_length=255, verbose_name='Статус верификации пользователя')),
                ('Language', models.CharField(blank=True, max_length=255, verbose_name='Язык')),
                ('balanceFull', models.CharField(blank=True, max_length=255, verbose_name='Баланс')),
                ('balance', models.CharField(blank=True, max_length=255, verbose_name='Баланс (число)')),
                ('ordersVolumeFull', models.CharField(blank=True, max_length=255, verbose_name='Оборот обменов')),
                ('ordersVolume', models.CharField(blank=True, max_length=255, verbose_name='Оборот обменов (число)')),
                ('referralLinkUrl', models.CharField(blank=True, max_length=255, verbose_name='Реферальная ссылка')),
                ('referralId', models.CharField(blank=True, max_length=255, verbose_name='Идентификатор реферера (0: нет)')),
                ('referralLogin', models.CharField(blank=True, max_length=255, verbose_name='Логин реферера (null: нет)')),
                ('referralsVolumeFull', models.CharField(blank=True, max_length=255, verbose_name='Оборот реферальных обменов')),
                ('referralsVolume', models.CharField(blank=True, max_length=255, verbose_name='Оборот реферальных обменов (число)')),
                ('rewardPercentFull', models.CharField(blank=True, max_length=255, verbose_name='Вознаграждение по реферальной программе')),
                ('rewardPercent', models.CharField(blank=True, max_length=255, verbose_name='Вознаграждение по реферальной программе (число)')),
                ('investmentsVolumeFull', models.CharField(blank=True, max_length=255, verbose_name='Оборот инвестиций')),
                ('investmentsVolume', models.CharField(blank=True, max_length=255, verbose_name='Оборот инвестиций (число)')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['registeredDate'],
            },
        ),
        migrations.CreateModel(
            name='Users_PCCNTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TG_Contact', models.CharField(max_length=255, verbose_name='Ник в Телеграм')),
                ('PCCNTR', models.CharField(max_length=255, verbose_name='Код Центра прибыли и затрат')),
                ('ExchangePointID', models.CharField(max_length=255, verbose_name='ID обменнника')),
                ('Name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('Surname', models.CharField(max_length=255, verbose_name='Имя')),
                ('Otchestvo', models.CharField(blank=True, max_length=255, verbose_name='Отчество (при наличии)')),
                ('GENDER', models.CharField(max_length=255, verbose_name='Пол')),
                ('COUNTRY', models.CharField(max_length=255, verbose_name='Страна')),
                ('CITY', models.CharField(max_length=255, verbose_name='Город')),
                ('Language', models.CharField(max_length=255, verbose_name='Язык')),
                ('ContactType', models.CharField(max_length=255, verbose_name='Тип контакта')),
                ('registeredDate', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('balanceFull', models.CharField(blank=True, max_length=255, verbose_name='Баланс')),
                ('balance', models.CharField(blank=True, max_length=255, verbose_name='Баланс (число)')),
                ('bonusFull', models.CharField(blank=True, max_length=255, verbose_name='Бонус')),
                ('bonus', models.CharField(blank=True, max_length=255, verbose_name='Бонус (число)')),
                ('ordersVolumeFull', models.CharField(blank=True, max_length=255, verbose_name='Оборот обменов')),
                ('ordersVolume', models.CharField(blank=True, max_length=255, verbose_name='Оборот обменов (число)')),
                ('referralsVolumeFull', models.CharField(blank=True, max_length=255, verbose_name='Оборот реферальных обменов')),
                ('referralsVolume', models.CharField(blank=True, max_length=255, verbose_name='Оборот реферальных обменов (число)')),
                ('rewardPercentFull', models.CharField(blank=True, max_length=255, verbose_name='Вознаграждение по реферальной программе')),
                ('rewardPercent', models.CharField(blank=True, max_length=255, verbose_name='Вознаграждение по реферальной программе (число)')),
                ('investmentsVolumeFull', models.CharField(blank=True, max_length=255, verbose_name='Оборот инвестиций')),
                ('investmentsVolume', models.CharField(blank=True, max_length=255, verbose_name='Оборот инвестиций (число)')),
            ],
            options={
                'verbose_name': 'Обменник',
                'verbose_name_plural': 'Обменники',
                'ordering': ['TG_Contact'],
            },
        ),
    ]
