# Generated by Django 4.2.5 on 2023-10-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0002_users_pccntr_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_pccntr',
            name='ExchangePointID',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID обменнника'),
        ),
    ]
