# Generated by Django 4.2.5 on 2023-10-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0003_alter_users_pccntr_exchangepointid'),
    ]

    operations = [
        migrations.CreateModel(
            name='testtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя')),
            ],
        ),
        migrations.AlterField(
            model_name='pccntr',
            name='PCCNTR_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Код Центра прибыли и затрат'),
        ),
        migrations.AlterField(
            model_name='pccntr',
            name='PCCNTR_name',
            field=models.CharField(max_length=255, verbose_name='Наименование Центра прибыли и затрат'),
        ),
    ]
