# Generated by Django 4.2.5 on 2023-10-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0004_testtable_alter_pccntr_pccntr_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtable',
            old_name='username',
            new_name='users_to_choose',
        ),
    ]
