# Generated by Django 4.2.5 on 2023-10-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0005_rename_username_testtable_users_to_choose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtable',
            name='users_to_choose',
        ),
        migrations.AddField(
            model_name='testtable',
            name='users_to_choose',
            field=models.ManyToManyField(blank=True, null=True, to='testsite.users'),
        ),
    ]
