# Generated by Django 4.2.5 on 2023-10-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0006_remove_testtable_users_to_choose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtable',
            name='users_to_choose',
        ),
        migrations.AddField(
            model_name='testtable',
            name='users_to_choose',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
