# Generated by Django 4.2.5 on 2023-10-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0007_remove_testtable_users_to_choose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCCNTR_ExchP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExchangePointID', models.CharField(max_length=255, verbose_name='ID обменника')),
                ('PCCNTR', models.CharField(max_length=255, verbose_name='Центр прибыли и затрат')),
                ('ContactType', models.CharField(max_length=255, verbose_name='Тип пользователя')),
                ('ExchangePointCountry', models.CharField(max_length=255, verbose_name='Страна')),
                ('ExchangePointCity', models.CharField(max_length=255, verbose_name='Город')),
                ('ExchangePointName', models.CharField(max_length=255, verbose_name='Наименование обменника')),
                ('ExchangePointOfficeCourier', models.CharField(max_length=255, verbose_name='Тип доставки')),
                ('ExchangePointDeals', models.CharField(blank=True, max_length=255, verbose_name='Тип сделки')),
                ('Monday', models.BooleanField(blank=True, verbose_name='Дни работы (Понедельник)')),
                ('Tuesday', models.BooleanField(blank=True, verbose_name='Дни работы (Вторник)')),
                ('Wednesday', models.BooleanField(blank=True, verbose_name='Дни работы (Среда)')),
                ('Thursday', models.BooleanField(blank=True, verbose_name='Дни работы (Четверг)')),
                ('Friday', models.BooleanField(blank=True, verbose_name='Дни работы (Пятница)')),
                ('Saturday', models.BooleanField(blank=True, verbose_name='Дни работы (Суббота)')),
                ('Sunday', models.BooleanField(blank=True, verbose_name='Дни работы (Воскресенье)')),
                ('ExchangePointOpenHours_Workingdays', models.CharField(blank=True, max_length=255, verbose_name='Время работы (будние дни)')),
                ('ExchangePointOpenHours_Weekends', models.CharField(blank=True, max_length=255, verbose_name='Время работы (выходные)')),
                ('ExchangePointAddress', models.CharField(max_length=2000, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Орг. структура обменников',
                'verbose_name_plural': 'Орг. структура обменника',
                'ordering': ['ExchangePointID'],
            },
        ),
    ]
