# Generated by Django 4.2.5 on 2023-10-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0010_ep_exchangeid_pccntr_opertypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ep_exchangeid',
            name='ExchangePointCity',
        ),
        migrations.RemoveField(
            model_name='ep_exchangeid',
            name='ExchangePointCountry',
        ),
    ]
