# Generated by Django 4.2.5 on 2023-10-09 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0011_remove_ep_exchangeid_exchangepointcity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pccntr_opertypes',
            name='PCCNTR_Name',
        ),
    ]
