# Generated by Django 4.2.5 on 2023-10-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0016_remove_pccntr_exchp_balancepercentfull_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefillBalanceRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('TG_Contact', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('Blockchain', models.CharField(max_length=255, verbose_name='Блокчейн для перевода')),
                ('balance_Amount', models.IntegerField(verbose_name='Сумма для пополнения')),
                ('Payment_data', models.CharField(max_length=255, verbose_name='Данные платежа')),
            ],
            options={
                'verbose_name': 'Ордер',
                'verbose_name_plural': 'Ордеры',
                'ordering': ['CreatedDate'],
            },
        ),
    ]
