# Generated by Django 4.2.5 on 2023-11-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0018_balance_delete_refillbalancerequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pccntr_exchp',
            name='ExchangePointAddress',
        ),
        migrations.RemoveField(
            model_name='pccntr_exchp',
            name='ExchangePointOpenHours_Weekends',
        ),
        migrations.RemoveField(
            model_name='pccntr_exchp',
            name='ExchangePointOpenHours_Workingdays',
        ),
        migrations.RemoveField(
            model_name='pccntr_exchp',
            name='Friday',
        ),
        migrations.RemoveField(
            model_name='pccntr_exchp',
            name='Monday',
        ),
        migrations.RemoveField(
            model_name='pccntr_exchp',
            name='Saturday',
        ),
        migrations.RemoveField(
            model_name='pccntr_exchp',
            name='Sunday',
        ),
        migrations.RemoveField(
            model_name='pccntr_exchp',
            name='Thursday',
        ),
        migrations.RemoveField(
            model_name='pccntr_exchp',
            name='Tuesday',
        ),
        migrations.RemoveField(
            model_name='pccntr_exchp',
            name='Wednesday',
        ),
        migrations.RemoveField(
            model_name='users_pccntr',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='users_pccntr',
            name='balanceFull',
        ),
        migrations.RemoveField(
            model_name='users_pccntr',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='users_pccntr',
            name='bonusFull',
        ),
        migrations.RemoveField(
            model_name='users_pccntr',
            name='investmentsVolume',
        ),
        migrations.RemoveField(
            model_name='users_pccntr',
            name='investmentsVolumeFull',
        ),
        migrations.RemoveField(
            model_name='users_pccntr',
            name='ordersVolume',
        ),
        migrations.RemoveField(
            model_name='users_pccntr',
            name='ordersVolumeFull',
        ),
        migrations.RemoveField(
            model_name='users_pccntr',
            name='referralsVolume',
        ),
        migrations.RemoveField(
            model_name='users_pccntr',
            name='referralsVolumeFull',
        ),
        migrations.RemoveField(
            model_name='users_pccntr',
            name='rewardPercent',
        ),
        migrations.RemoveField(
            model_name='users_pccntr',
            name='rewardPercentFull',
        ),
        migrations.AddField(
            model_name='users_pccntr',
            name='ExchangePointAddress',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='users_pccntr',
            name='ExchangePointOpenHours_Weekends',
            field=models.CharField(blank=True, max_length=255, verbose_name='Время работы (выходные)'),
        ),
        migrations.AddField(
            model_name='users_pccntr',
            name='ExchangePointOpenHours_Workingdays',
            field=models.CharField(blank=True, max_length=255, verbose_name='Время работы (будние дни)'),
        ),
        migrations.AddField(
            model_name='users_pccntr',
            name='Friday',
            field=models.BooleanField(blank=True, default=0, verbose_name='Дни работы (Пятница)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_pccntr',
            name='Monday',
            field=models.BooleanField(blank=True, default=0, verbose_name='Дни работы (Понедельник)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_pccntr',
            name='Saturday',
            field=models.BooleanField(blank=True, default=0, verbose_name='Дни работы (Суббота)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_pccntr',
            name='Sunday',
            field=models.BooleanField(blank=True, default=0, verbose_name='Дни работы (Воскресенье)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_pccntr',
            name='Thursday',
            field=models.BooleanField(blank=True, default=0, verbose_name='Дни работы (Четверг)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_pccntr',
            name='Tuesday',
            field=models.BooleanField(blank=True, default=0, verbose_name='Дни работы (Вторник)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_pccntr',
            name='Wednesday',
            field=models.BooleanField(blank=True, default=0, verbose_name='Дни работы (Среда)'),
            preserve_default=False,
        ),
    ]
