# Generated by Django 4.2.5 on 2023-11-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0021_balance_payment_type_alter_users_pccntr_friday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Status',
            field=models.CharField(default='Создан', max_length=255, verbose_name='Статус заявки'),
        ),
    ]
