# Generated by Django 4.2.5 on 2023-12-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0023_quotesrc_delete_testtable_remove_users_pccntr_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='balance',
        ),
        migrations.AddField(
            model_name='users',
            name='bonusPercentFull',
            field=models.IntegerField(blank=True, default=0, verbose_name='Бонус'),
        ),
        migrations.AlterField(
            model_name='users',
            name='balanceFull',
            field=models.IntegerField(blank=True, default=0, verbose_name='Баланс'),
        ),
    ]
