# Generated by Django 4.2.5 on 2023-12-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0024_remove_users_balance_users_bonuspercentfull_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pccntr_opertypes',
            name='Bank',
            field=models.CharField(default=0, max_length=255, verbose_name='Банк'),
            preserve_default=False,
        ),
    ]
