# Generated by Django 4.2.5 on 2023-12-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0027_alter_orders_receiveamount_alter_orders_sendamount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinOfficeFrom',
            new_name='FinOffice',
        ),
        migrations.AlterModelOptions(
            name='finoffice',
            options={'ordering': ['FinOfficeType'], 'verbose_name': 'Финансовое учреждение', 'verbose_name_plural': 'Финансовые учреждения'},
        ),
    ]
