# Generated by Django 4.2.5 on 2023-12-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0028_rename_finofficefrom_finoffice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinOfficeFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FinOfficeType', models.CharField(max_length=255, verbose_name='Тип финансового учреждения')),
                ('Name_RUS', models.CharField(blank=True, max_length=255, verbose_name='Наименования финансового учреждения (RUS)')),
                ('Name_ENG', models.CharField(blank=True, max_length=255, verbose_name='Наименования финансового учреждения (ENG)')),
                ('Name_DEU', models.CharField(blank=True, max_length=255, verbose_name='Наименования финансового учреждения (DEU)')),
                ('Name_SRB', models.CharField(blank=True, max_length=255, verbose_name='Наименования финансового учреждения (SRB)')),
                ('FinOfficeCurr', models.CharField(max_length=255, verbose_name='Валюта финансового учреждения')),
            ],
            options={
                'verbose_name': 'Финансовое учреждение',
                'verbose_name_plural': 'Финансовые учреждения',
                'ordering': ['FinOfficeType'],
            },
        ),
    ]
