# Generated by Django 4.2.5 on 2023-12-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0029_finofficefrom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinOfficeFrom',
        ),
    ]
