# Generated by Django 4.2.5 on 2023-12-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0030_delete_finofficefrom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, max_length=255, verbose_name='Номер ордера')),
                ('request_id', models.IntegerField(blank=True, max_length=255, verbose_name='Номер заявки')),
                ('date', models.DateTimeField(blank=True, max_length=255, verbose_name='Дата создания')),
                ('date_unix', models.DateTimeField(blank=True, max_length=255, verbose_name='Дата создания (Unix Timestamp)')),
                ('user_id', models.IntegerField(blank=True, max_length=255, verbose_name='Идентификатор пользователя')),
                ('profit_centers', models.CharField(blank=True, max_length=255, verbose_name='Центры прибыли и затрат')),
                ('exchanger_id', models.IntegerField(blank=True, max_length=255, verbose_name='ID обменника')),
                ('exchange_point_id', models.IntegerField(blank=True, max_length=255, verbose_name='Идентификатор направления обмена')),
                ('price_type', models.CharField(blank=True, max_length=255, verbose_name='Тип цены')),
                ('currency_code_out', models.CharField(blank=True, max_length=255, verbose_name='Код отдаваемой валюты')),
                ('currency_code_in', models.CharField(blank=True, max_length=255, verbose_name='Код получаемой валюты')),
                ('sum_out', models.CharField(blank=True, max_length=255, verbose_name='Отдаваемая сумма (число)')),
                ('sum_in', models.IntegerField(blank=True, max_length=255, verbose_name='Получаемая сумма (число)')),
                ('number_of_decimal', models.IntegerField(blank=True, max_length=255, verbose_name='Количество знаков после запятой получаемой валюты')),
                ('sum_usd', models.IntegerField(blank=True, max_length=255, verbose_name='Сумма обмена в эквиваленте USD')),
                ('sum_eur', models.IntegerField(blank=True, max_length=255, verbose_name='Сумма обмена в эквиваленте EUR')),
                ('fin_office_to', models.CharField(blank=True, max_length=255, verbose_name='Финансовые учреждения Получатели')),
                ('deal_date', models.DateTimeField(blank=True, max_length=255, verbose_name='Дата сделки число')),
                ('interval_of_deal_date', models.CharField(blank=True, max_length=255, verbose_name='Интервал времени сделки')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Город')),
                ('delivery_type', models.CharField(blank=True, max_length=255, verbose_name='Тип доставки')),
                ('limit_order', models.CharField(blank=True, max_length=255, verbose_name='Лимит ордера')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('staus_id', models.CharField(blank=True, max_length=255, verbose_name='Идентификатор статуса')),
                ('deal_id', models.IntegerField(blank=True, max_length=255, verbose_name='Номер сделки')),
            ],
        ),
    ]
