# Generated by Django 4.2.5 on 2023-12-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0033_rename_exchangerequest_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='OperType',
            new_name='ExchangeID',
        ),
    ]
