# Generated by Django 4.2.5 on 2023-12-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0036_alter_requests_exchangepointid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='status_id',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='requests',
            name='ExchangeID',
            field=models.CharField(blank=True, max_length=255, verbose_name='Идентификатор направления обмена'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='send_amount',
            field=models.IntegerField(blank=True, verbose_name='Отдаваемая сумма (число)'),
        ),
    ]
