# Generated by Django 4.2.5 on 2024-02-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0040_remove_requests_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='ExchangePointID',
        ),
        migrations.RemoveField(
            model_name='pccntr_exchp',
            name='balanceFull',
        ),
        migrations.RemoveField(
            model_name='pccntr_exchp',
            name='bonusPercentFull',
        ),
        migrations.AddField(
            model_name='balance',
            name='PCCNTR',
            field=models.CharField(default=0, max_length=255, verbose_name='Центр прибыли и затрат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pccntr',
            name='balanceFull',
            field=models.IntegerField(blank=True, default=0, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='pccntr',
            name='bonusPercentFull',
            field=models.IntegerField(blank=True, default=0, verbose_name='Бонус'),
        ),
    ]
