# Generated by Django 4.2.5 on 2024-03-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0043_remove_pccntr_exchp_exchangepointdeals'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Page',
            field=models.CharField(default='-', max_length=2000, verbose_name='Страница обращения'),
        ),
    ]
