# Generated by Django 4.2.5 on 2024-05-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0045_currency_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_source',
            name='Value',
            field=models.FloatField(verbose_name='Курс валют'),
        ),
    ]
