# Generated by Django 4.2.5 on 2024-05-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0046_alter_currency_source_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency_source',
            name='Bank',
            field=models.CharField(default=0, max_length=255, verbose_name='Банк'),
            preserve_default=False,
        ),
    ]
