# Generated by Django 4.2.5 on 2024-08-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0048_exchangeid_finofficefrom_exchangeid_finofficeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency_source',
            name='OperTypeName',
            field=models.CharField(default=0, max_length=255, verbose_name='Направление сделки (для парсера)'),
            preserve_default=False,
        ),
    ]
