# Generated by Django 4.2.5 on 2024-08-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0049_currency_source_opertypename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pccntr_opertypes',
            name='Bank',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк'),
        ),
    ]
