# Generated by Django 4.2.5 on 2024-08-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0050_alter_pccntr_opertypes_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='pccntr_opertypes',
            name='FinOfficeFrom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип отправления'),
        ),
        migrations.AddField(
            model_name='pccntr_opertypes',
            name='FinOfficeTo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип получения'),
        ),
        migrations.AddField(
            model_name='pccntr_opertypes',
            name='ReceiveTransferType',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип получаемой валюты'),
        ),
        migrations.AddField(
            model_name='pccntr_opertypes',
            name='SendTransferType',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип отправляемой валюты'),
        ),
    ]
