# Generated by Django 4.2.5 on 2024-08-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0051_pccntr_opertypes_finofficefrom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='FinOfficeTo',
            field=models.CharField(default=0, max_length=255, verbose_name='Финансовое учреждение получателя'),
            preserve_default=False,
        ),
    ]
