# Generated by Django 4.2.5 on 2024-08-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0052_orders_finofficeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency_source',
            name='Bank',
        ),
        migrations.RemoveField(
            model_name='currency_source',
            name='OperTypeName',
        ),
    ]
