# Generated by Django 4.2.5 on 2024-08-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0053_remove_currency_source_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeid',
            name='FinOfficeFrom',
        ),
        migrations.RemoveField(
            model_name='exchangeid',
            name='FinOfficeTo',
        ),
        migrations.RemoveField(
            model_name='pccntr_opertypes',
            name='Bank',
        ),
        migrations.RemoveField(
            model_name='pccntr_opertypes',
            name='FinOfficeFrom',
        ),
        migrations.RemoveField(
            model_name='pccntr_opertypes',
            name='FinOfficeTo',
        ),
    ]
