# Generated by Django 4.2.5 on 2024-08-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0054_remove_exchangeid_finofficefrom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='comment',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='date',
            new_name='CreatedDate',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='deal_date',
            new_name='DealDate',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='deal_id',
            new_name='DealID',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='delivery_type',
            new_name='DeliveryType',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='fin_office_to',
            new_name='FinOfficeTo',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='order_id',
            new_name='OrderID',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='limit_order',
            new_name='OrderLimit',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='price_type',
            new_name='PriceType',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='receive_amount',
            new_name='ReceiveAmount',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='receive_currency_ISO',
            new_name='ReceiveCurrencyISO',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='send_amount',
            new_name='SendAmount',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='send_currency_ISO',
            new_name='SendCurrencyISO',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='time_interval',
            new_name='TimeInterval',
        ),
    ]
