# Generated by Django 4.2.5 on 2024-08-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0055_rename_city_requests_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='DealID',
            new_name='Deal_ID',
        ),
    ]
