# Generated by Django 4.2.5 on 2024-08-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0056_rename_dealid_requests_deal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='FinOfficeFrom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Финансовые учреждения Отправители'),
        ),
    ]
