# Generated by Django 4.2.5 on 2024-08-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0058_remove_requests_number_of_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('PCCNTR', models.CharField(max_length=255, verbose_name='Центр прибыли и затрат')),
                ('Reserve_Amount', models.IntegerField(verbose_name='Сумма для пополнения')),
                ('OrderID', models.IntegerField(blank=True, verbose_name='Номер ордера')),
                ('RequestID', models.IntegerField(blank=True, verbose_name='Номер предложения')),
                ('DealID', models.IntegerField(blank=True, verbose_name='Номер сделки')),
                ('Payment_data', models.CharField(blank=True, max_length=255, verbose_name='Данные платежа')),
                ('Payment_type', models.CharField(blank=True, max_length=255, verbose_name='Тип платежа')),
            ],
            options={
                'verbose_name': 'Изменение резерва',
                'verbose_name_plural': 'Изменения резерва',
                'ordering': ['-CreatedDate'],
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TG_Contact', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('ContactType', models.CharField(max_length=255, verbose_name='Тип контакта')),
                ('PCCNTR', models.CharField(blank=True, max_length=255, verbose_name='Код Центра прибыли и затрат')),
                ('ExchangePointID', models.CharField(blank=True, max_length=255, verbose_name='ID обменнника')),
                ('Unread', models.BooleanField(default=False, verbose_name='Прочитано уведомление или нет')),
                ('NoticeDate', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время уведомления')),
                ('Text', models.CharField(max_length=100000, verbose_name='Текст уведомления')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-Unread'],
            },
        ),
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['-CreatedDate'], 'verbose_name': 'Изменение баланса', 'verbose_name_plural': 'Изменения баланса'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='Deal_ID',
            field=models.IntegerField(blank=True, verbose_name='Номер сделки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='RequestID',
            field=models.IntegerField(blank=True, verbose_name='Номер предложения'),
        ),
    ]
