# Generated by Django 4.2.5 on 2024-08-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0059_dealreserve_notifications_alter_balance_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Deal_ID',
            new_name='DealID',
        ),
        migrations.RenameField(
            model_name='pccntr',
            old_name='balanceFull',
            new_name='Balance',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='Deal_ID',
            new_name='DealID',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='sum_eur',
            new_name='SumEUR',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='sum_usd',
        ),
        migrations.AddField(
            model_name='pccntr',
            name='Reserve',
            field=models.IntegerField(blank=True, default=0, verbose_name='Резерв по сделкам'),
        ),
        migrations.AddField(
            model_name='requests',
            name='SumUSDT',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма обмена в эквиваленте USDT'),
            preserve_default=False,
        ),
    ]
