# Generated by Django 4.2.5 on 2024-08-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0060_rename_deal_id_orders_dealid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealreserve',
            name='Payment_data',
        ),
        migrations.RemoveField(
            model_name='dealreserve',
            name='Payment_type',
        ),
    ]
