# Generated by Django 4.2.5 on 2024-08-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0061_remove_dealreserve_payment_data_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balance',
            new_name='Payments',
        ),
    ]
