# Generated by Django 4.2.5 on 2024-08-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0062_rename_balance_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='EP_Bonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCCNTR', models.CharField(max_length=255, verbose_name='Центр прибыли и затрат')),
                ('ExchangePointID', models.CharField(max_length=255, verbose_name='ID обменника')),
                ('ExchangeTransferID', models.CharField(max_length=10000, verbose_name='Тип сделки')),
                ('EP_Bonus', models.CharField(max_length=20000, verbose_name='Диапазон скидок')),
            ],
            options={
                'verbose_name': 'Обменник и скидки',
                'verbose_name_plural': 'Обменники и скидки',
                'ordering': ['PCCNTR', 'ExchangePointID'],
            },
        ),
    ]
