from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views
from .views import *

urlpatterns = [
    path('home/start_page/<str:usertype>/', index, name='home'),
    path('check_usertype/', check_usertype, name='check_usertype'),
    path('check_usertype/choose_exchange/<str:usertype>/', choose_exchange, name='choose_exchange'),
    path('success/', success, name='success'),
    path('P2Pmarket/', P2Pmarket, name='P2Pmarket'),
    path('P2Pmarket/ExchangeOrder/', P2Pmarket_Exchange_order, name='P2Pmarket_Exchange_order'),
    path('P2Pmarket/ExchangeOrder/load_pay_type_sell/', load_pay_type_sell, name='load_pay_type_sell'),
    path('P2Pmarket/ExchangeOrder/load_pay_type_buy/', load_pay_type_buy, name='load_pay_type_buy'),
    path('P2Pmarket/ExchangeOrder/load_payment_method_from/', load_payment_method_from, name='load_payment_method_from'),
    path('P2Pmarket/ExchangeOrder/load_payment_method_to/', load_payment_method_to, name='load_payment_method_to'),
    path('P2Pmarket/ExchangeOrder/confirm/', P2Pmarket_Exchange_order_confirm, name='P2Pmarket_Exchange_order_confirm'),
    path('P2Pmarket/ExchangeOrder/final/', P2Pmarket_Exchange_order_final, name='P2Pmarket_Exchange_order_final'),
    path('P2Pmarket/ExchangeOrder/change/<int:num>/', P2Pmarket_change_Exchange_order, name='P2Pmarket_change_Exchange_order'),
    path('P2Pmarket/ExchangeOrder/change/<int:num>/load_pay_type_sell_num/', load_pay_type_sell_num, name='load_pay_type_sell_num'),
    path('P2Pmarket/ExchangeOrder/change/<int:num>/load_pay_type_buy_num/', load_pay_type_buy_num, name='load_pay_type_buy_num'),
    path('P2Pmarket/ExchangeOrder/change/<int:num>/load_payment_method_from_num/', load_payment_method_from_num,name='load_payment_method_from_num'),
    path('P2Pmarket/ExchangeOrder/change/<int:num>/load_payment_method_to_num/', load_payment_method_to_num, name='load_payment_method_to_num'),
    path('P2Pmarket/BulletinBoard/', P2Pmarket_Bulletin_board, name='P2Pmarket_Bulletin_board'),
    path('P2Pmarket/ChooseRequest/<int:num>/', P2Pmarket_Choose_Request, name='P2Pmarket_Choose_Request'),
    path('P2Pmarket/ExchangeRequest/<int:num>/', P2Pmarket_Exchange_request, name='P2Pmarket_Exchange_request'),
    path('P2Pmarket/BulletinBoard/delete/confirm/<int:num>/', P2Pmarket_Bulletin_board_delete_confirm, name='P2Pmarket_Bulletin_board_delete_confirm'),
    path('P2Pmarket/BulletinBoard/delete/final/<int:num>/', P2Pmarket_Bulletin_board_delete_final, name='P2Pmarket_Bulletin_board_delete_final'),
    path('P2Pmarket/DealBoard/', P2Pmarket_Deal_board, name='P2Pmarket_Deal_board'),
    path('P2Pmarket/chat/<int:num>/', chat, name='chat'),
    path('P2Pmarket/room/<str:room_name>/', room, name='room'),
    path('send_message/', send_message, name='send_message'),
    path('send_file/', send_file, name='send_file'),
    path('home/safety/', safety, name='safety'),
    path('home/notifications/', Notification, name='Notification'),
    path('home/notifications/confirm_order_changes/<int:num>/', Confirm_order_changes, name='Confirm_order_changes'),
    path('home/notifications/decline_order_changes/<int:num>/', Decline_order_changes, name='Decline_order_changes'),
    path('home/general/', general_settings, name='general_settings'),
    path('home/general/personal/', general_settings_personal, name='general_settings_personal'),
    path('home/general/personal/load_cities/', load_cities, name='load_cities'),
    path('home/general/pccntr/', general_settings_pccntr, name='general_settings_pccntr'),
    path('home/general/exchange_points/', general_settings_exchange_points, name='general_settings_exchange_points'),
    path('home/general/exchange_points/exchange_structure/change/<str:exch_name>/', general_settings_change_exchange_structure, name='general_settings_change_exchange_structure'),
    path('home/general/exchange_points/exchange_structure/change/1/exch_org/', general_settings_change_exchange_structure_1, name='general_settings_change_exchange_structure_1'),
    path('home/general/exchange_points/exchange_structure/change/1/exch_org/final/', general_settings_change_exchange_structure_1_final, name='general_settings_change_exchange_structure_1_final'),
    path('home/general/exchange_points/exchange_structure/change/2/main_info/', general_settings_change_exchange_structure_2, name='general_settings_change_exchange_structure_2'),
    path('home/general/exchange_points/exchange_structure/change/3/employee_menu/', general_settings_change_exchange_structure_3_menu, name='general_settings_change_exchange_structure_3_menu'),
    path('home/general/exchange_points/exchange_structure/change/3/employee_menu/edit/<str:employee_name>/', general_settings_change_exchange_structure_3_employee, name='general_settings_change_exchange_structure_3_employee'),
    path('home/general/exchange_points/exchange_structure/change/3/employee_menu/edit/<str:employee_name>/load_cities_text/', load_cities_text, name='load_cities_text'),
    path('home/general/exchange_points/exchange_structure/change/3/employee_menu/delete/<str:employee_name>/', general_settings_change_exchange_structure_3_delete_employee, name='general_settings_change_exchange_structure_3_delete_employee'),
    path('home/general/exchange_points/exchange_structure/change/3/employee_menu/delete/final/<str:employee_name>/', general_settings_change_exchange_structure_3_delete_employee_final, name='general_settings_change_exchange_structure_3_delete_employee_final'),
    path('home/general/exchange_points/exchange_structure/new/1/', general_settings_exchange_structure_new_1, name="general_settings_exchange_structure_new_1"),
    path('home/general/exchange_points/exchange_structure/new/1/confirm/<int:num>/', general_settings_exchange_structure_new_1_confirm, name="general_settings_exchange_structure_new_1_confirm"),
    path('home/general/exchange_points/exchange_structure/new/1/final/', general_settings_exchange_structure_new_1_final, name="general_settings_exchange_structure_new_1_final"),
    path('home/general/exchange_points/exchange_structure/new/2/', general_settings_exchange_structure_new_2, name="general_settings_exchange_structure_new_2"),
    path('home/general/exchange_points/exchange_structure/new/3/<int:num>/', general_settings_exchange_structure_new_3, name="general_settings_exchange_structure_new_3"),
    path('home/general/exchange_points/exchange_structure/new/3/<int:num>/load_cities_num/', load_cities_num, name='load_cities_num'),
    path('home/general/exchange_points/exchange_structure/new/3/confirm/<int:num>/', general_settings_exchange_structure_new_3_confirm, name="general_settings_exchange_structure_new_3_confirm"),
    path('home/general/exchange_points/exchange_structure/new/3/final/', general_settings_exchange_structure_new_3_final, name="general_settings_exchange_structure_new_3_final"),
    path('home/general/exchange_points/exchange_deals/change/1/', general_settings_change_exchange_deals_1, name='general_settings_change_exchange_deals_1'),
    path('home/general/exchange_points/exchange_deals/change/1/load_pay_type_sell/', load_pay_type_sell, name='load_pay_type_sell'),
    path('home/general/exchange_points/exchange_deals/change/1/load_pay_type_buy/', load_pay_type_buy, name='load_pay_type_buy'),
    path('home/general/exchange_points/exchange_deals/change/1/load_payment_method_from/', load_payment_method_from, name='load_payment_method_from'),
    path('home/general/exchange_points/exchange_deals/change/1/load_payment_method_to/', load_payment_method_to, name='load_payment_method_to'),
    path('home/general/exchange_points/exchange_deals/change/2/', general_settings_change_exchange_deals_2, name='general_settings_change_exchange_deals_2'),
    path('home/general/exchange_points/exchange_deals/bonus/change/', general_settings_change_exchange_deals_bonus_2, name='general_settings_change_exchange_deals_bonus_2'),
    path('home/general/exchange_points/exchange_deals/exch_rate_source/change/', general_settings_change_exchange_rate_source, name='general_settings_change_exchange_rate_source'),
    path('home/general/exchange_points/exchange_deals/new/', general_settings_exchange_deals_new, name='general_settings_exchange_deals_new'),
    path('home/general/exchange_points/exchange_deals/new/load_pay_type_sell/', load_pay_type_sell, name='load_pay_type_sell'),
    path('home/general/exchange_points/exchange_deals/new/load_pay_type_buy/', load_pay_type_buy, name='load_pay_type_buy'),
    path('home/general/exchange_points/exchange_deals/new/load_payment_method_from/', load_payment_method_from,name='load_payment_method_from'),
    path('home/general/exchange_points/exchange_deals/new/load_payment_method_to/', load_payment_method_to, name='load_payment_method_to'),
    path('home/general/exchange_points/exchange_deals/add/new/', general_settings_exchange_deals_add_new, name='general_settings_exchange_deals_add_new'),
    path('home/general/exchange_points/exchange_deals/add/new/load_pay_type_sell/', load_pay_type_sell, name='load_pay_type_sell'),
    path('home/general/exchange_points/exchange_deals/add/new/load_pay_type_buy/', load_pay_type_buy, name='load_pay_type_buy'),
    path('home/general/exchange_points/exchange_deals/add/new/load_payment_method_from/', load_payment_method_from,name='load_payment_method_from'),
    path('home/general/exchange_points/exchange_deals/add/new/load_payment_method_to/', load_payment_method_to, name='load_payment_method_to'),
    path('home/general/exchange_points/exchange_deals/exch_rate_source/new/', general_settings_exchange_rate_source_new, name='general_settings_exchange_rate_source_new'),
    path('home/general/exchange_points/exchange_deals/delete/', general_settings_delete_exchange_deals, name='general_settings_delete_exchange_deals'),
    path('home/general/exchange_points/exchange_deals/delete/load_pay_type_sell/', load_pay_type_sell, name='load_pay_type_sell'),
    path('home/general/exchange_points/exchange_deals/delete/load_pay_type_buy/', load_pay_type_buy, name='load_pay_type_buy'),
    path('home/general/exchange_points/exchange_deals/delete/load_payment_method_from/', load_payment_method_from, name='load_payment_method_from'),
    path('home/general/exchange_points/exchange_deals/delete/load_payment_method_to/', load_payment_method_to, name='load_payment_method_to'),
    path('home/general/exchange_points/exchange_deals/delete/confirm/', general_settings_delete_exchange_deals_confirm, name='general_settings_delete_exchange_deals_confirm'),
    path('home/general/exchange_points/exchange_deals/delete/final/', general_settings_delete_exchange_deals_final, name='general_settings_delete_exchange_deals_final'),
    path('home/balance/', balance_settings, name='balance_settings'),
    path('home/balance/refill_balance/', balance_settings_refill_balance, name='balance_settings_refill_balance'),
    path('home/balance/withdraw_funds/', balance_settings_withdraw_funds, name='balance_settings_withdraw_funds'),
    path('register/1/', RegisterUser.as_view(), name='register'),
    path('', LoginUser.as_view(), name='login'),
    path('logout/', LogOut, name='logout'),
    path('register/delete_user/', delete_user, name='delete_user'),
    path('register/2/', register2, name='register2'),
    path('register/2/load_cities/', load_cities, name='load_cities'),
    path('register/delete_user_2/', delete_user_2, name='delete_user_2'),
    path('register/pccntr/', register_pccntr, name='register_pccntr'),
    path('register/delete_pccntr/', delete_pccntr, name='delete_pccntr'),
    path('register/delete_org/', delete_org, name='delete_org'),
    path('register/delete_exch/', delete_exch, name='delete_exch'),
    path('register/delete_empl/', delete_empl, name='delete_empl'),
    path('register/delete_exch_operations/<str:exch_name>/', delete_exch_operations, name='delete_exch_operations'),
    path('home/feedback/<int:num>/<int:num2>/', feedback, name='feedback'),
    path('change_password/', PasswordChangeView.as_view(template_name='testsite/change_password.html', success_url=reverse_lazy('change_password_done')), name='change_password'),
    path('change_password/done/', PasswordChangeDoneView.as_view(template_name='testsite/change_password_done.html'), name='change_password_done'),
    path('email_confirm/<int:num>/', email_confirm, name='email_confirm'),
    path('email_confirm_repeat/<int:num>/', email_confirm_repeat, name='email_confirm_repeat'),
    path('home/safety/password_reset/', passwordreset, name='password_reset'),
    path('home/safety/password_reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='testsite/password_reset_confirm.html', success_url=reverse_lazy('password_reset_complete')), name='password_reset_confirm'),
    path('home/safety/password_reset/complete/', PasswordResetCompleteView.as_view(template_name='testsite/password_reset_complete.html'), name='password_reset_complete'),
    path('home/safety/email_reset/', emailreset, name='email_reset'),
    path('home/safety/email_reset/complete/', emailresetcomplete, name='email_reset_complete'),

]
